// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Todo.DAL
{

    // TodoItems
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class TodoItem
    {

        ///<summary>
        /// 流水識別碼
        ///</summary>
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 分類Id
        ///</summary>
        public byte CategoryId { get; set; } // CategoryId

        ///<summary>
        /// 標題
        ///</summary>
        public string Title { get; set; } // Title (length: 30)

        ///<summary>
        /// 詳細內容
        ///</summary>
        public string Description { get; set; } // Description (length: 200)

        ///<summary>
        /// 是否完成（True:已完成 False:尚未完成）
        ///</summary>
        public bool IsFinish { get; set; } // IsFinish

        ///<summary>
        /// 截止日期
        ///</summary>
        public System.DateTime? DeadLineOn { get; set; } // DeadLineOn

        public TodoItem()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
